import { cc, dlopen, FFIType, JSCallback } from "bun:ffi";
import source from "../libs/main.c" with { type: "file" };

const {
    symbols: {
        _uiInit,
        _uiUninit,
        _uiFreeInitError,
        _uiMain,
        _uiMainSteps,
        _uiMainStep,
        _uiQuit,
        _uiQueueMain,
        _uiTimer,
        _uiOnShouldQuit,
        _uiFreeText,
        _uiControlDestroy,
        _uiControlHandle,
        _uiControlParent,
        _uiControlSetParent,
        _uiControlToplevel,
        _uiControlVisible,
        _uiControlShow,
        _uiControlHide,
        _uiControlEnabled,
        _uiControlEnable,
        _uiControlDisable,
        _uiAllocControl,
        _uiFreeControl,
        _uiControlVerifySetParent,
        _uiControlEnabledToUser,
        _uiUserBugCannotSetParentOnToplevel,
        _uiWindowTitle,
        _uiWindowSetTitle,
        _uiWindowPosition,
        _uiWindowSetPosition,
        _uiWindowOnPositionChanged,
        _uiWindowContentSize,
        _uiWindowSetContentSize,
        _uiWindowFullscreen,
        _uiWindowSetFullscreen,
        _uiWindowOnContentSizeChanged,
        _uiWindowOnClosing,
        _uiWindowOnFocusChanged,
        _uiWindowFocused,
        _uiWindowBorderless,
        _uiWindowSetBorderless,
        _uiWindowSetChild,
        _uiWindowMargined,
        _uiWindowSetMargined,
        _uiWindowResizeable,
        _uiWindowSetResizeable,
        _uiNewWindow,
        _uiButtonText,
        _uiButtonSetText,
        _uiButtonOnClicked,
        _uiNewButton,
        _uiBoxAppend,
        _uiBoxNumChildren,
        _uiBoxDelete,
        _uiBoxPadded,
        _uiBoxSetPadded,
        _uiNewHorizontalBox,
        _uiNewVerticalBox,
        _uiCheckboxText,
        _uiCheckboxSetText,
        _uiCheckboxOnToggled,
        _uiCheckboxChecked,
        _uiCheckboxSetChecked,
        _uiNewCheckbox,
        _uiEntryText,
        _uiEntrySetText,
        _uiEntryOnChanged,
        _uiEntryReadOnly,
        _uiEntrySetReadOnly,
        _uiNewEntry,
        _uiNewPasswordEntry,
        _uiNewSearchEntry,
        _uiLabelText,
        _uiLabelSetText,
        _uiNewLabel,
        _uiTabAppend,
        _uiTabInsertAt,
        _uiTabDelete,
        _uiTabNumPages,
        _uiTabMargined,
        _uiTabSetMargined,
        _uiNewTab,
        _uiGroupTitle,
        _uiGroupSetTitle,
        _uiGroupSetChild,
        _uiGroupMargined,
        _uiGroupSetMargined,
        _uiNewGroup,
        _uiSpinboxValue,
        _uiSpinboxSetValue,
        _uiSpinboxOnChanged,
        _uiNewSpinbox,
        _uiSliderValue,
        _uiSliderSetValue,
        _uiSliderHasToolTip,
        _uiSliderSetHasToolTip,
        _uiSliderOnChanged,
        _uiSliderOnReleased,
        _uiSliderSetRange,
        _uiNewSlider,
        _uiProgressBarValue,
        _uiProgressBarSetValue,
        _uiNewProgressBar,
        _uiNewHorizontalSeparator,
        _uiNewVerticalSeparator,
        _uiComboboxAppend,
        _uiComboboxInsertAt,
        _uiComboboxDelete,
        _uiComboboxClear,
        _uiComboboxNumItems,
        _uiComboboxSelected,
        _uiComboboxSetSelected,
        _uiComboboxOnSelected,
        _uiNewCombobox,
        _uiEditableComboboxAppend,
        _uiEditableComboboxText,
        _uiEditableComboboxSetText,
        _uiEditableComboboxOnChanged,
        _uiNewEditableCombobox,
        _uiRadioButtonsAppend,
        _uiRadioButtonsSelected,
        _uiRadioButtonsSetSelected,
        _uiRadioButtonsOnSelected,
        _uiNewRadioButtons,
        _uiDateTimePickerTime,
        _uiDateTimePickerSetTime,
        _uiDateTimePickerOnChanged,
        _uiNewDateTimePicker,
        _uiNewDatePicker,
        _uiNewTimePicker,
        _uiMultilineEntryText,
        _uiMultilineEntrySetText,
        _uiMultilineEntryAppend,
        _uiMultilineEntryOnChanged,
        _uiMultilineEntryReadOnly,
        _uiMultilineEntrySetReadOnly,
        _uiNewMultilineEntry,
        _uiNewNonWrappingMultilineEntry,
        _uiMenuItemEnable,
        _uiMenuItemDisable,
        _uiMenuItemOnClicked,
        _uiMenuItemChecked,
        _uiMenuItemSetChecked,
        _uiMenuAppendItem,
        _uiMenuAppendCheckItem,
        _uiMenuAppendQuitItem,
        _uiMenuAppendPreferencesItem,
        _uiMenuAppendAboutItem,
        _uiMenuAppendSeparator,
        _uiNewMenu,
        _uiOpenFile,
        _uiOpenFolder,
        _uiSaveFile,
        _uiMsgBox,
        _uiMsgBoxError,
        _uiAreaSetSize,
        _uiAreaQueueRedrawAll,
        _uiAreaScrollTo,
        _uiAreaBeginUserWindowMove,
        _uiAreaBeginUserWindowResize,
        _uiNewArea,
        _uiNewScrollingArea,
        _uiDrawNewPath,
        _uiDrawFreePath,
        _uiDrawPathNewFigure,
        _uiDrawPathNewFigureWithArc,
        _uiDrawPathLineTo,
        _uiDrawPathArcTo,
        _uiDrawPathBezierTo,
        _uiDrawPathCloseFigure,
        _uiDrawPathAddRectangle,
        _uiDrawPathEnded,
        _uiDrawPathEnd,
        _uiDrawStroke,
        _uiDrawFill,
        _uiDrawMatrixSetIdentity,
        _uiDrawMatrixTranslate,
        _uiDrawMatrixScale,
        _uiDrawMatrixRotate,
        _uiDrawMatrixSkew,
        _uiDrawMatrixMultiply,
        _uiDrawMatrixInvertible,
        _uiDrawMatrixInvert,
        _uiDrawMatrixTransformPoint,
        _uiDrawMatrixTransformSize,
        _uiDrawTransform,
        _uiDrawClip,
        _uiDrawSave,
        _uiDrawRestore,
        _uiFreeAttribute,
        _uiAttributeGetType,
        _uiNewFamilyAttribute,
        _uiAttributeFamily,
        _uiNewSizeAttribute,
        _uiAttributeSize,
        _uiNewWeightAttribute,
        _uiAttributeWeight,
        _uiNewItalicAttribute,
        _uiAttributeItalic,
        _uiNewStretchAttribute,
        _uiAttributeStretch,
        _uiNewColorAttribute,
        _uiAttributeColor,
        _uiNewBackgroundAttribute,
        _uiNewUnderlineAttribute,
        _uiAttributeUnderline,
        _uiNewUnderlineColorAttribute,
        _uiAttributeUnderlineColor,
        _uiNewOpenTypeFeatures,
        _uiFreeOpenTypeFeatures,
        _uiOpenTypeFeaturesClone,
        _uiOpenTypeFeaturesAdd,
        _uiOpenTypeFeaturesRemove,
        _uiOpenTypeFeaturesGet,
        _uiOpenTypeFeaturesForEach,
        _uiNewFeaturesAttribute,
        _uiAttributeFeatures,
        _uiNewAttributedString,
        _uiFreeAttributedString,
        _uiAttributedStringString,
        _uiAttributedStringLen,
        _uiAttributedStringAppendUnattributed,
        _uiAttributedStringInsertAtUnattributed,
        _uiAttributedStringDelete,
        _uiAttributedStringSetAttribute,
        _uiAttributedStringForEachAttribute,
        _uiAttributedStringNumGraphemes,
        _uiAttributedStringByteIndexToGrapheme,
        _uiAttributedStringGraphemeToByteIndex,
        _uiLoadControlFont,
        _uiFreeFontDescriptor,
        _uiDrawNewTextLayout,
        _uiDrawFreeTextLayout,
        _uiDrawText,
        _uiDrawTextLayoutExtents,
        _uiFontButtonFont,
        _uiFontButtonOnChanged,
        _uiNewFontButton,
        _uiFreeFontButtonFont,
        _uiColorButtonColor,
        _uiColorButtonSetColor,
        _uiColorButtonOnChanged,
        _uiNewColorButton,
        _uiFormAppend,
        _uiFormNumChildren,
        _uiFormDelete,
        _uiFormPadded,
        _uiFormSetPadded,
        _uiNewForm,
        _uiGridAppend,
        _uiGridInsertAt,
        _uiGridPadded,
        _uiGridSetPadded,
        _uiNewGrid,
        _uiNewImage,
        _uiFreeImage,
        _uiImageAppend,
        _uiFreeTableValue,
        _uiTableValueGetType,
        _uiNewTableValueString,
        _uiTableValueString,
        _uiNewTableValueImage,
        _uiTableValueImage,
        _uiNewTableValueInt,
        _uiTableValueInt,
        _uiNewTableValueColor,
        _uiTableValueColor,
        _uiNewTableModel,
        _uiFreeTableModel,
        _uiTableModelRowInserted,
        _uiTableModelRowChanged,
        _uiTableModelRowDeleted,
        _uiTableAppendTextColumn,
        _uiTableAppendImageColumn,
        _uiTableAppendCheckboxColumn,
        _uiTableAppendCheckboxTextColumn,
        _uiTableAppendProgressBarColumn,
        _uiTableAppendButtonColumn,
        _uiTableAppendImageTextColumn,
        _uiTableHeaderVisible,
        _uiTableHeaderSetVisible,
        _uiNewTable,
        _uiTableOnRowClicked,
        _uiTableOnRowDoubleClicked,
        _uiTableHeaderSetSortIndicator,
        _uiTableHeaderSortIndicator,
        _uiTableHeaderOnClicked,
        _uiTableColumnWidth,
        _uiTableColumnSetWidth,
        _uiTableGetSelectionMode,
        _uiTableSetSelectionMode,
        _uiTableOnSelectionChanged,
        _uiTableGetSelection,
        _uiTableSetSelection,
        _uiFreeTableSelection
    },
} = cc({
    source,
    flags: '-Llibs',
    library: ["libui"],
    include: ["./libs/include"],
    symbols: {
        _uiInit: {
            args: [],
            returns: 'cstring',
        },
        _uiUninit: {
            args: [],
            returns: 'ptr',
        },
        _uiFreeInitError: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiMain: {
            args: [],
            returns: 'ptr',
        },
        _uiMainSteps: {
            args: [],
            returns: 'ptr',
        },
        _uiMainStep: {
            args: ['i32'],
            returns: 'ptr',
        },
        _uiQuit: {
            args: [],
            returns: 'ptr',
        },
        _uiQueueMain: {
            args: [],
            returns: 'ptr',
        },
        _uiTimer: {
            args: ['i32', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiOnShouldQuit: {
            args: ['ptr', 'callback'],
            returns: 'void',
        },
        _uiFreeText: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlDestroy: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlHandle: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlParent: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlSetParent: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiControlToplevel: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlVisible: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlShow: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlHide: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlEnabled: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlEnable: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlDisable: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiAllocControl: {
            args: ['ptr', 'i32', 'i32', 'cstring'],
            returns: 'ptr',
        },
        _uiFreeControl: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiControlVerifySetParent: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiControlEnabledToUser: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiUserBugCannotSetParentOnToplevel: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiWindowTitle: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiWindowSetTitle: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiWindowPosition: {
            args: ['ptr', 'ptr', 'ptr'],
            returns: 'void',
        },
        _uiWindowSetPosition: {
            args: ['ptr', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiWindowOnPositionChanged: {
            args: ['ptr', 'ptr', 'ptr'],
            returns: 'void',
        },
        _uiWindowContentSize: {
            args: ['ptr', 'ptr', 'ptr'],
            returns: 'void',
        },
        _uiWindowSetContentSize: {
            args: ['ptr', 'i32', 'i32'],
            returns: 'void',
        },
        _uiWindowFullscreen: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiWindowSetFullscreen: {
            args: ['ptr', 'bool'],
            returns: 'ptr',
        },
        _uiWindowOnContentSizeChanged: {
            args: ['ptr', 'ptr', 'ptr'],
            returns: 'void',
        },
        _uiWindowOnClosing: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiWindowOnFocusChanged: {
            args: ['ptr', 'ptr', 'ptr'],
            returns: 'void',
        },
        _uiWindowFocused: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiWindowBorderless: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiWindowSetBorderless: {
            args: ['ptr', 'bool'],
            returns: 'ptr',
        },
        _uiWindowSetChild: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiWindowMargined: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiWindowSetMargined: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiWindowResizeable: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiWindowSetResizeable: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiNewWindow: {
            args: ['cstring', 'i32', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiButtonText: {
            args: ['ptr'],
            returns: 'cstring',
        },
        _uiButtonSetText: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiButtonOnClicked: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiNewButton: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiBoxAppend: {
            args: ['ptr', 'ptr', 'bool'],
            returns: 'ptr',
        },
        _uiBoxNumChildren: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiBoxDelete: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiBoxPadded: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiBoxSetPadded: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiNewHorizontalBox: {
            args: [],
            returns: 'ptr',
        },
        _uiNewVerticalBox: {
            args: [],
            returns: 'ptr',
        },
        _uiCheckboxText: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiCheckboxSetText: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiCheckboxOnToggled: {
            args: ['ptr', 'callback'],
            returns: 'ptr',
        },
        _uiCheckboxChecked: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiCheckboxSetChecked: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiNewCheckbox: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiEntryText: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiEntrySetText: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiEntryOnChanged: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'ptr',
        },
        _uiEntryReadOnly: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiEntrySetReadOnly: {
            args: ['ptr', 'bool'],
            returns: 'ptr',
        },
        _uiNewEntry: {
            args: [],
            returns: 'ptr',
        },
        _uiNewPasswordEntry: {
            args: [],
            returns: 'ptr',
        },
        _uiNewSearchEntry: {
            args: [],
            returns: 'ptr',
        },
        _uiLabelText: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiLabelSetText: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiNewLabel: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiTabAppend: {
            args: ['ptr', 'cstring', 'ptr'],
            returns: 'ptr',
        },
        _uiTabInsertAt: {
            args: ['ptr', 'cstring', 'i32', 'ptr'],
            returns: 'ptr',
        },
        _uiTabDelete: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiTabNumPages: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiTabMargined: {
            args: ['ptr', 'i32'],
            returns: 'i32',
        },
        _uiTabSetMargined: {
            args: ['ptr', 'i32', 'bool'],
            returns: 'ptr',
        },
        _uiNewTab: {
            args: [],
            returns: 'ptr',
        },
        _uiGroupTitle: {
            args: ['ptr'],
            returns: 'cstring',
        },
        _uiGroupSetTitle: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiGroupSetChild: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiGroupMargined: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiGroupSetMargined: {
            args: ['ptr', 'bool'],
            returns: 'void',
        },
        _uiNewGroup: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiSpinboxValue: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiSpinboxSetValue: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiSpinboxOnChanged: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiNewSpinbox: {
            args: ['i32', 'i32'],
            returns: 'ptr',
        },
        _uiSliderValue: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiSliderSetValue: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiSliderHasToolTip: {
            args: ['ptr'],
            returns: 'bool',
        },
        _uiSliderSetHasToolTip: {
            args: ['ptr', 'bool'],
            returns: 'ptr',
        },
        _uiSliderOnChanged: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'ptr',
        },
        _uiSliderOnReleased: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'ptr',
        },
        _uiSliderSetRange: {
            args: ['ptr', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiNewSlider: {
            args: ['i32', 'i32'],
            returns: 'ptr',
        },
        _uiProgressBarValue: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiProgressBarSetValue: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiNewProgressBar: {
            args: [],
            returns: 'ptr',
        },
        _uiNewHorizontalSeparator: {
            args: [],
            returns: 'ptr',
        },
        _uiNewVerticalSeparator: {
            args: [],
            returns: 'ptr',
        },
        _uiComboboxAppend: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiComboboxInsertAt: {
            args: ['ptr', 'i32', 'cstring'],
            returns: 'ptr',
        },
        _uiComboboxDelete: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiComboboxClear: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiComboboxNumItems: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiComboboxSelected: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiComboboxSetSelected: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiComboboxOnSelected: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiNewCombobox: {
            args: [],
            returns: 'ptr',
        },
        _uiEditableComboboxAppend: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiEditableComboboxText: {
            args: ['ptr'],
            returns: 'cstring',
        },
        _uiEditableComboboxSetText: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiEditableComboboxOnChanged: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiNewEditableCombobox: {
            args: [],
            returns: 'ptr',
        },
        _uiRadioButtonsAppend: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiRadioButtonsSelected: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiRadioButtonsSetSelected: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiRadioButtonsOnSelected: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiNewRadioButtons: {
            args: [],
            returns: 'ptr',
        },
        _uiDateTimePickerTime: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiDateTimePickerSetTime: {
            args: ['ptr', 'ptr'],
            returns: 'void',
        },
        _uiDateTimePickerOnChanged: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiNewDateTimePicker: {
            args: [],
            returns: 'ptr',
        },
        _uiNewDatePicker: {
            args: [],
            returns: 'ptr',
        },
        _uiNewTimePicker: {
            args: [],
            returns: 'ptr',
        },
        _uiMultilineEntryText: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiMultilineEntrySetText: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiMultilineEntryAppend: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiMultilineEntryOnChanged: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiMultilineEntryReadOnly: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiMultilineEntrySetReadOnly: {
            args: ['ptr', 'bool'],
            returns: 'void',
        },
        _uiNewMultilineEntry: {
            args: [],
            returns: 'ptr',
        },
        _uiNewNonWrappingMultilineEntry: {
            args: [],
            returns: 'ptr',
        },
        _uiMenuItemEnable: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiMenuItemDisable: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiMenuItemOnClicked: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiMenuItemChecked: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiMenuItemSetChecked: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiMenuAppendItem: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiMenuAppendCheckItem: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiMenuAppendQuitItem: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiMenuAppendPreferencesItem: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiMenuAppendAboutItem: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiMenuAppendSeparator: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewMenu: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiOpenFile: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiOpenFolder: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiSaveFile: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiMsgBox: {
            args: ['ptr', 'cstring', 'cstring'],
            returns: 'ptr',
        },
        _uiMsgBoxError: {
            args: ['ptr', 'cstring', 'cstring'],
            returns: 'ptr',
        },
        _uiAreaSetSize: {
            args: ['ptr', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiAreaQueueRedrawAll: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiAreaScrollTo: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiAreaBeginUserWindowMove: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiAreaBeginUserWindowResize: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiNewArea: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewScrollingArea: {
            args: ['ptr', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiDrawNewPath: {
            args: ['int'],
            returns: 'ptr',
        },
        _uiDrawFreePath: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiDrawPathNewFigure: {
            args: ['ptr', 'f64', 'f64'],
            returns: 'void',
        },
        _uiDrawPathNewFigureWithArc: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64', 'f64', 'i32'],
            returns: 'void',
        },
        _uiDrawPathLineTo: {
            args: ['ptr', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiDrawPathArcTo: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64', 'f64', 'i32'],
            returns: 'void',
        },
        _uiDrawPathBezierTo: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64', 'f64', 'f64'],
            returns: 'void',
        },
        _uiDrawPathCloseFigure: {
            args: ['ptr'],
            returns: 'void',
        },
        _uiDrawPathAddRectangle: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64'],
            returns: 'void',
        },
        _uiDrawPathEnded: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiDrawPathEnd: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiDrawStroke: {
            args: ['ptr', 'ptr', 'ptr', 'ptr'],
            returns: 'void',
        },
        _uiDrawFill: {
            args: ['ptr', 'ptr', 'ptr'],
            returns: 'void',
        },
        _uiDrawMatrixSetIdentity: {
            args: ['ptr'],
            returns: 'void',
        },
        _uiDrawMatrixTranslate: {
            args: ['ptr', 'f64', 'f64'],
            returns: 'void',
        },
        _uiDrawMatrixScale: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64'],
            returns: 'void',
        },
        _uiDrawMatrixRotate: {
            args: ['ptr', 'f64', 'f64', 'f64'],
            returns: 'void',
        },
        _uiDrawMatrixSkew: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiDrawMatrixMultiply: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiDrawMatrixInvertible: {
            args: ['ptr'],
            returns: 'bool',
        },
        _uiDrawMatrixInvert: {
            args: ['ptr'],
            returns: 'bool',
        },
        _uiDrawMatrixTransformPoint: {
            args: ['ptr', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiDrawMatrixTransformSize: {
            args: ['ptr', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiDrawTransform: {
            args: ['ptr', 'ptr'],
            returns: 'void',
        },
        _uiDrawClip: {
            args: ['ptr', 'ptr'],
            returns: 'void',
        },
        _uiDrawSave: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiDrawRestore: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiFreeAttribute: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiAttributeGetType: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewFamilyAttribute: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiAttributeFamily: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewSizeAttribute: {
            args: ['f64'],
            returns: 'ptr',
        },
        _uiAttributeSize: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewWeightAttribute: {
            args: ['i32'],
            returns: 'ptr',
        },
        _uiAttributeWeight: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewItalicAttribute: {
            args: ['i32'],
            returns: 'ptr',
        },
        _uiAttributeItalic: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewStretchAttribute: {
            args: ['i32'],
            returns: 'ptr',
        },
        _uiAttributeStretch: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewColorAttribute: {
            args: ['f64', 'f64', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiAttributeColor: {
            args: ['ptr', 'ptr', 'ptr', 'ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiNewBackgroundAttribute: {
            args: ['f64', 'f64', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiNewUnderlineAttribute: {
            args: ['i32'],
            returns: 'ptr',
        },
        _uiAttributeUnderline: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewUnderlineColorAttribute: {
            args: ['i32', 'f64', 'f64', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiAttributeUnderlineColor: {
            args: ['ptr', 'ptr', 'ptr', 'ptr', 'ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiNewOpenTypeFeatures: {
            args: [],
            returns: 'ptr',
        },
        _uiFreeOpenTypeFeatures: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiOpenTypeFeaturesClone: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiOpenTypeFeaturesAdd: {
            args: ['ptr', 'ptr', 'ptr', 'ptr', 'ptr', 'i32'],
            returns: 'ptr',
        },
        _uiOpenTypeFeaturesRemove: {
            args: ['ptr', 'ptr', 'ptr', 'ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiOpenTypeFeaturesGet: {
            args: ['ptr', 'ptr', 'ptr', 'ptr', 'ptr', 'i32'],
            returns: 'ptr',
        },
        _uiOpenTypeFeaturesForEach: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiNewFeaturesAttribute: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiAttributeFeatures: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewAttributedString: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiFreeAttributedString: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiAttributedStringString: {
            args: ['ptr'],
            returns: 'cstring',
        },
        _uiAttributedStringLen: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiAttributedStringAppendUnattributed: {
            args: ['ptr', 'cstring'],
            returns: 'ptr',
        },
        _uiAttributedStringInsertAtUnattributed: {
            args: ['ptr', 'cstring', 'i32'],
            returns: 'ptr',
        },
        _uiAttributedStringDelete: {
            args: ['ptr', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiAttributedStringSetAttribute: {
            args: ['ptr', 'ptr', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiAttributedStringForEachAttribute: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiAttributedStringNumGraphemes: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiAttributedStringByteIndexToGrapheme: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiAttributedStringGraphemeToByteIndex: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiLoadControlFont: {
            args: ['ptr'],
            returns: 'void',
        },
        _uiFreeFontDescriptor: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiDrawNewTextLayout: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiDrawFreeTextLayout: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiDrawText: {
            args: ['ptr', 'ptr', 'f64', 'f64'],
            returns: 'void',
        },
        _uiDrawTextLayoutExtents: {
            args: ['ptr', 'ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiFontButtonFont: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiFontButtonOnChanged: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiNewFontButton: {
            args: [],
            returns: 'ptr',
        },
        _uiFreeFontButtonFont: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiColorButtonColor: {
            args: ['ptr', 'ptr', 'ptr', 'ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiColorButtonSetColor: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64'],
            returns: 'void',
        },
        _uiColorButtonOnChanged: {
            args: ['ptr', 'callback', 'ptr'],
            returns: 'void',
        },
        _uiNewColorButton: {
            args: [],
            returns: 'ptr',
        },
        _uiFormAppend: {
            args: ['ptr', 'cstring', 'ptr', 'i32'],
            returns: 'ptr',
        },
        _uiFormNumChildren: {
            args: ['ptr'],
            returns: 'int',
        },
        _uiFormDelete: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiFormPadded: {
            args: ['ptr'],
            returns: 'bool',
        },
        _uiFormSetPadded: {
            args: ['ptr', 'bool'],
            returns: 'ptr',
        },
        _uiNewForm: {
            args: [],
            returns: 'ptr',
        },
        _uiGridAppend: {
            args: ['ptr', 'ptr', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'],
            returns: 'void',
        },
        _uiGridInsertAt: {
            args: ['ptr', 'ptr', 'ptr', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'],
            returns: 'void',
        },
        _uiGridPadded: {
            args: ['ptr'],
            returns: 'bool',
        },
        _uiGridSetPadded: {
            args: ['ptr', 'bool'],
            returns: 'void',
        },
        _uiNewGrid: {
            args: [],
            returns: 'ptr',
        },
        _uiNewImage: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiFreeImage: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiImageAppend: {
            args: ['ptr', 'i32', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiFreeTableValue: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiTableValueGetType: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewTableValueString: {
            args: ['cstring'],
            returns: 'ptr',
        },
        _uiTableValueString: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewTableValueImage: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiTableValueImage: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiNewTableValueInt: {
            args: ['i32'],
            returns: 'ptr',
        },
        _uiTableValueInt: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiNewTableValueColor: {
            args: ['f64', 'f64', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiTableValueColor: {
            args: ['ptr', 'f64', 'f64', 'f64', 'f64'],
            returns: 'ptr',
        },
        _uiNewTableModel: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiFreeTableModel: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiTableModelRowInserted: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiTableModelRowChanged: {
            args: ['ptr', 'i32'],
            returns: 'ptr',
        },
        _uiTableModelRowDeleted: {
            args: ['ptr', 'i32'],
            returns: 'void',
        },
        _uiTableAppendTextColumn: {
            args: ['ptr', 'cstring', 'i32', 'i32', 'ptr'],
            returns: 'ptr',
        },
        _uiTableAppendImageColumn: {
            args: ['ptr', 'cstring', 'i32'],
            returns: 'ptr',
        },
        _uiTableAppendCheckboxColumn: {
            args: ['ptr', 'cstring', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiTableAppendCheckboxTextColumn: {
            args: ['ptr', 'cstring', 'i32', 'i32', 'i32', 'i32', 'ptr'],
            returns: 'ptr',
        },
        _uiTableAppendProgressBarColumn: {
            args: ['ptr', 'cstring', 'i32'],
            returns: 'ptr',
        },
        _uiTableAppendButtonColumn: {
            args: ['ptr', 'cstring', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiTableAppendImageTextColumn: {
            args: ['ptr', 'cstring', 'i32', 'i32', 'i32', 'ptr'],
            returns: 'ptr',
        },
        _uiTableHeaderVisible: {
            args: ['ptr'],
            returns: 'bool',
        },
        _uiTableHeaderSetVisible: {
            args: ['ptr', 'bool'],
            returns: 'ptr',
        },
        _uiNewTable: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiTableOnRowClicked: {
            args: ['ptr', 'callback'],
            returns: 'void',
        },
        _uiTableOnRowDoubleClicked: {
            args: ['ptr', 'callback'],
            returns: 'void',
        },
        _uiTableHeaderSetSortIndicator: {
            args: ['ptr', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiTableHeaderSortIndicator: {
            args: ['ptr', 'i32'],
            returns: 'i32',
        },
        _uiTableHeaderOnClicked: {
            args: ['ptr', 'callback'],
            returns: 'void',
        },
        _uiTableColumnWidth: {
            args: ['ptr', 'i32'],
            returns: 'i32',
        },
        _uiTableColumnSetWidth: {
            args: ['ptr', 'i32', 'i32'],
            returns: 'ptr',
        },
        _uiTableGetSelectionMode: {
            args: ['ptr'],
            returns: 'i32',
        },
        _uiTableSetSelectionMode: {
            args: ['ptr', 'i32'],
            returns: 'void',
        },
        _uiTableOnSelectionChanged: {
            args: ['ptr', 'callback'],
            returns: 'void',
        },
        _uiTableGetSelection: {
            args: ['ptr'],
            returns: 'ptr',
        },
        _uiTableSetSelection: {
            args: ['ptr', 'ptr'],
            returns: 'ptr',
        },
        _uiFreeTableSelection: {
            args: ['ptr'],
            returns: 'ptr',
        }
    },
});

export {
    _uiInit,
    _uiUninit,
    _uiFreeInitError,
    _uiMain,
    _uiMainSteps,
    _uiMainStep,
    _uiQuit,
    _uiQueueMain,
    _uiTimer,
    _uiOnShouldQuit,
    _uiFreeText,
    _uiControlDestroy,
    _uiControlHandle,
    _uiControlParent,
    _uiControlSetParent,
    _uiControlToplevel,
    _uiControlVisible,
    _uiControlShow,
    _uiControlHide,
    _uiControlEnabled,
    _uiControlEnable,
    _uiControlDisable,
    _uiAllocControl,
    _uiFreeControl,
    _uiControlVerifySetParent,
    _uiControlEnabledToUser,
    _uiUserBugCannotSetParentOnToplevel,
    _uiWindowTitle,
    _uiWindowSetTitle,
    _uiWindowPosition,
    _uiWindowSetPosition,
    _uiWindowOnPositionChanged,
    _uiWindowContentSize,
    _uiWindowSetContentSize,
    _uiWindowFullscreen,
    _uiWindowSetFullscreen,
    _uiWindowOnContentSizeChanged,
    _uiWindowOnClosing,
    _uiWindowOnFocusChanged,
    _uiWindowFocused,
    _uiWindowBorderless,
    _uiWindowSetBorderless,
    _uiWindowSetChild,
    _uiWindowMargined,
    _uiWindowSetMargined,
    _uiWindowResizeable,
    _uiWindowSetResizeable,
    _uiNewWindow,
    _uiButtonText,
    _uiButtonSetText,
    _uiButtonOnClicked,
    _uiNewButton,
    _uiBoxAppend,
    _uiBoxNumChildren,
    _uiBoxDelete,
    _uiBoxPadded,
    _uiBoxSetPadded,
    _uiNewHorizontalBox,
    _uiNewVerticalBox,
    _uiCheckboxText,
    _uiCheckboxSetText,
    _uiCheckboxOnToggled,
    _uiCheckboxChecked,
    _uiCheckboxSetChecked,
    _uiNewCheckbox,
    _uiEntryText,
    _uiEntrySetText,
    _uiEntryOnChanged,
    _uiEntryReadOnly,
    _uiEntrySetReadOnly,
    _uiNewEntry,
    _uiNewPasswordEntry,
    _uiNewSearchEntry,
    _uiLabelText,
    _uiLabelSetText,
    _uiNewLabel,
    _uiTabAppend,
    _uiTabInsertAt,
    _uiTabDelete,
    _uiTabNumPages,
    _uiTabMargined,
    _uiTabSetMargined,
    _uiNewTab,
    _uiGroupTitle,
    _uiGroupSetTitle,
    _uiGroupSetChild,
    _uiGroupMargined,
    _uiGroupSetMargined,
    _uiNewGroup,
    _uiSpinboxValue,
    _uiSpinboxSetValue,
    _uiSpinboxOnChanged,
    _uiNewSpinbox,
    _uiSliderValue,
    _uiSliderSetValue,
    _uiSliderHasToolTip,
    _uiSliderSetHasToolTip,
    _uiSliderOnChanged,
    _uiSliderOnReleased,
    _uiSliderSetRange,
    _uiNewSlider,
    _uiProgressBarValue,
    _uiProgressBarSetValue,
    _uiNewProgressBar,
    _uiNewHorizontalSeparator,
    _uiNewVerticalSeparator,
    _uiComboboxAppend,
    _uiComboboxInsertAt,
    _uiComboboxDelete,
    _uiComboboxClear,
    _uiComboboxNumItems,
    _uiComboboxSelected,
    _uiComboboxSetSelected,
    _uiComboboxOnSelected,
    _uiNewCombobox,
    _uiEditableComboboxAppend,
    _uiEditableComboboxText,
    _uiEditableComboboxSetText,
    _uiEditableComboboxOnChanged,
    _uiNewEditableCombobox,
    _uiRadioButtonsAppend,
    _uiRadioButtonsSelected,
    _uiRadioButtonsSetSelected,
    _uiRadioButtonsOnSelected,
    _uiNewRadioButtons,
    _uiDateTimePickerTime,
    _uiDateTimePickerSetTime,
    _uiDateTimePickerOnChanged,
    _uiNewDateTimePicker,
    _uiNewDatePicker,
    _uiNewTimePicker,
    _uiMultilineEntryText,
    _uiMultilineEntrySetText,
    _uiMultilineEntryAppend,
    _uiMultilineEntryOnChanged,
    _uiMultilineEntryReadOnly,
    _uiMultilineEntrySetReadOnly,
    _uiNewMultilineEntry,
    _uiNewNonWrappingMultilineEntry,
    _uiMenuItemEnable,
    _uiMenuItemDisable,
    _uiMenuItemOnClicked,
    _uiMenuItemChecked,
    _uiMenuItemSetChecked,
    _uiMenuAppendItem,
    _uiMenuAppendCheckItem,
    _uiMenuAppendQuitItem,
    _uiMenuAppendPreferencesItem,
    _uiMenuAppendAboutItem,
    _uiMenuAppendSeparator,
    _uiNewMenu,
    _uiOpenFile,
    _uiOpenFolder,
    _uiSaveFile,
    _uiMsgBox,
    _uiMsgBoxError,
    _uiAreaSetSize,
    _uiAreaQueueRedrawAll,
    _uiAreaScrollTo,
    _uiAreaBeginUserWindowMove,
    _uiAreaBeginUserWindowResize,
    _uiNewArea,
    _uiNewScrollingArea,
    _uiDrawNewPath,
    _uiDrawFreePath,
    _uiDrawPathNewFigure,
    _uiDrawPathNewFigureWithArc,
    _uiDrawPathLineTo,
    _uiDrawPathArcTo,
    _uiDrawPathBezierTo,
    _uiDrawPathCloseFigure,
    _uiDrawPathAddRectangle,
    _uiDrawPathEnded,
    _uiDrawPathEnd,
    _uiDrawStroke,
    _uiDrawFill,
    _uiDrawMatrixSetIdentity,
    _uiDrawMatrixTranslate,
    _uiDrawMatrixScale,
    _uiDrawMatrixRotate,
    _uiDrawMatrixSkew,
    _uiDrawMatrixMultiply,
    _uiDrawMatrixInvertible,
    _uiDrawMatrixInvert,
    _uiDrawMatrixTransformPoint,
    _uiDrawMatrixTransformSize,
    _uiDrawTransform,
    _uiDrawClip,
    _uiDrawSave,
    _uiDrawRestore,
    _uiFreeAttribute,
    _uiAttributeGetType,
    _uiNewFamilyAttribute,
    _uiAttributeFamily,
    _uiNewSizeAttribute,
    _uiAttributeSize,
    _uiNewWeightAttribute,
    _uiAttributeWeight,
    _uiNewItalicAttribute,
    _uiAttributeItalic,
    _uiNewStretchAttribute,
    _uiAttributeStretch,
    _uiNewColorAttribute,
    _uiAttributeColor,
    _uiNewBackgroundAttribute,
    _uiNewUnderlineAttribute,
    _uiAttributeUnderline,
    _uiNewUnderlineColorAttribute,
    _uiAttributeUnderlineColor,
    _uiNewOpenTypeFeatures,
    _uiFreeOpenTypeFeatures,
    _uiOpenTypeFeaturesClone,
    _uiOpenTypeFeaturesAdd,
    _uiOpenTypeFeaturesRemove,
    _uiOpenTypeFeaturesGet,
    _uiOpenTypeFeaturesForEach,
    _uiNewFeaturesAttribute,
    _uiAttributeFeatures,
    _uiNewAttributedString,
    _uiFreeAttributedString,
    _uiAttributedStringString,
    _uiAttributedStringLen,
    _uiAttributedStringAppendUnattributed,
    _uiAttributedStringInsertAtUnattributed,
    _uiAttributedStringDelete,
    _uiAttributedStringSetAttribute,
    _uiAttributedStringForEachAttribute,
    _uiAttributedStringNumGraphemes,
    _uiAttributedStringByteIndexToGrapheme,
    _uiAttributedStringGraphemeToByteIndex,
    _uiLoadControlFont,
    _uiFreeFontDescriptor,
    _uiDrawNewTextLayout,
    _uiDrawFreeTextLayout,
    _uiDrawText,
    _uiDrawTextLayoutExtents,
    _uiFontButtonFont,
    _uiFontButtonOnChanged,
    _uiNewFontButton,
    _uiFreeFontButtonFont,
    _uiColorButtonColor,
    _uiColorButtonSetColor,
    _uiColorButtonOnChanged,
    _uiNewColorButton,
    _uiFormAppend,
    _uiFormNumChildren,
    _uiFormDelete,
    _uiFormPadded,
    _uiFormSetPadded,
    _uiNewForm,
    _uiGridAppend,
    _uiGridInsertAt,
    _uiGridPadded,
    _uiGridSetPadded,
    _uiNewGrid,
    _uiNewImage,
    _uiFreeImage,
    _uiImageAppend,
    _uiFreeTableValue,
    _uiTableValueGetType,
    _uiNewTableValueString,
    _uiTableValueString,
    _uiNewTableValueImage,
    _uiTableValueImage,
    _uiNewTableValueInt,
    _uiTableValueInt,
    _uiNewTableValueColor,
    _uiTableValueColor,
    _uiNewTableModel,
    _uiFreeTableModel,
    _uiTableModelRowInserted,
    _uiTableModelRowChanged,
    _uiTableModelRowDeleted,
    _uiTableAppendTextColumn,
    _uiTableAppendImageColumn,
    _uiTableAppendCheckboxColumn,
    _uiTableAppendCheckboxTextColumn,
    _uiTableAppendProgressBarColumn,
    _uiTableAppendButtonColumn,
    _uiTableAppendImageTextColumn,
    _uiTableHeaderVisible,
    _uiTableHeaderSetVisible,
    _uiNewTable,
    _uiTableOnRowClicked,
    _uiTableOnRowDoubleClicked,
    _uiTableHeaderSetSortIndicator,
    _uiTableHeaderSortIndicator,
    _uiTableHeaderOnClicked,
    _uiTableColumnWidth,
    _uiTableColumnSetWidth,
    _uiTableGetSelectionMode,
    _uiTableSetSelectionMode,
    _uiTableOnSelectionChanged,
    _uiTableGetSelection,
    _uiTableSetSelection,
    _uiFreeTableSelection
}